{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting xgboost\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/c1/24/5fe7237b2eca13ee0cfb100bec8c23f4e69ce9df852a64b0493d49dae4e0/xgboost-0.90-py2.py3-none-manylinux1_x86_64.whl (142.8MB)\n",
      "\u001b[K    100% |████████████████████████████████| 142.8MB 406kB/s eta 0:00:01   31% |██████████▎                     | 45.6MB 40.9MB/s eta 0:00:03    56% |██████████████████              | 80.6MB 51.6MB/s eta 0:00:02\n",
      "\u001b[?25hRequirement already satisfied: numpy in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from xgboost) (1.15.4)\n",
      "Requirement already satisfied: scipy in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from xgboost) (1.1.0)\n",
      "\u001b[31mfastai 1.0.50.post1 requires nvidia-ml-py3, which is not installed.\u001b[0m\n",
      "\u001b[31mthinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.0 which is incompatible.\u001b[0m\n",
      "Installing collected packages: xgboost\n",
      "Successfully installed xgboost-0.90\n",
      "\u001b[33mYou are using pip version 10.0.1, however version 19.1.1 is available.\n",
      "You should consider upgrading via the 'pip install --upgrade pip' command.\u001b[0m\n",
      "Collecting plotly_express\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/b2/2e/ce5d392f22ca54b23a81d3c74c611e1691851cf9395dc0e47e44648e83be/plotly_express-0.3.0-py2.py3-none-any.whl (74kB)\n",
      "\u001b[K    100% |████████████████████████████████| 81kB 1.7MB/s ta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: statsmodels>=0.9.0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from plotly_express) (0.9.0)\n",
      "Requirement already satisfied: patsy>=0.5 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from plotly_express) (0.5.0)\n",
      "Requirement already satisfied: pandas>=0.20.0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from plotly_express) (0.22.0)\n",
      "Collecting plotly>=3.10.0 (from plotly_express)\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/ff/75/3982bac5076d0ce6d23103c03840fcaec90c533409f9d82c19f54512a38a/plotly-3.10.0-py2.py3-none-any.whl (41.5MB)\n",
      "\u001b[K    100% |████████████████████████████████| 41.5MB 1.3MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: scipy>=0.18 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from plotly_express) (1.1.0)\n",
      "Requirement already satisfied: numpy>=1.11 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from plotly_express) (1.15.4)\n",
      "Requirement already satisfied: six in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from patsy>=0.5->plotly_express) (1.11.0)\n",
      "Requirement already satisfied: pytz>=2011k in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas>=0.20.0->plotly_express) (2018.4)\n",
      "Requirement already satisfied: python-dateutil>=2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas>=0.20.0->plotly_express) (2.7.3)\n",
      "Requirement already satisfied: requests in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from plotly>=3.10.0->plotly_express) (2.20.1)\n",
      "Requirement already satisfied: decorator>=4.0.6 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from plotly>=3.10.0->plotly_express) (4.3.0)\n",
      "Collecting retrying>=1.3.3 (from plotly>=3.10.0->plotly_express)\n",
      "  Downloading https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz\n",
      "Requirement already satisfied: nbformat>=4.2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from plotly>=3.10.0->plotly_express) (4.4.0)\n",
      "Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from requests->plotly>=3.10.0->plotly_express) (1.23)\n",
      "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from requests->plotly>=3.10.0->plotly_express) (3.0.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from requests->plotly>=3.10.0->plotly_express) (2019.3.9)\n",
      "Requirement already satisfied: idna<2.8,>=2.5 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from requests->plotly>=3.10.0->plotly_express) (2.6)\n",
      "Requirement already satisfied: ipython_genutils in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=3.10.0->plotly_express) (0.2.0)\n",
      "Requirement already satisfied: traitlets>=4.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=3.10.0->plotly_express) (4.3.2)\n",
      "Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=3.10.0->plotly_express) (2.6.0)\n",
      "Requirement already satisfied: jupyter_core in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=3.10.0->plotly_express) (4.4.0)\n",
      "Building wheels for collected packages: retrying\n",
      "  Running setup.py bdist_wheel for retrying ... \u001b[?25ldone\n",
      "\u001b[?25h  Stored in directory: /home/ubuntu/.cache/pip/wheels/d7/a9/33/acc7b709e2a35caa7d4cae442f6fe6fbf2c43f80823d46460c\n",
      "Successfully built retrying\n",
      "\u001b[31mfastai 1.0.50.post1 requires nvidia-ml-py3, which is not installed.\u001b[0m\n",
      "\u001b[31mthinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.0 which is incompatible.\u001b[0m\n",
      "\u001b[31mautovizwidget 0.12.7 has requirement plotly<3.0,>=1.10.0, but you'll have plotly 3.10.0 which is incompatible.\u001b[0m\n",
      "Installing collected packages: retrying, plotly, plotly-express\n",
      "  Found existing installation: plotly 2.7.0\n",
      "    Uninstalling plotly-2.7.0:\n",
      "      Successfully uninstalled plotly-2.7.0\n",
      "Successfully installed plotly-3.10.0 plotly-express-0.3.0 retrying-1.3.3\n",
      "\u001b[33mYou are using pip version 10.0.1, however version 19.1.1 is available.\n",
      "You should consider upgrading via the 'pip install --upgrade pip' command.\u001b[0m\n",
      "Collecting dfply\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/53/91/18ab48c64661252dadff685f8ddbc6f456302923918f488714ee2345d49b/dfply-0.3.3-py3-none-any.whl (612kB)\n",
      "\u001b[K    100% |████████████████████████████████| 614kB 21.9MB/s ta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: pandas in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from dfply) (0.22.0)\n",
      "Requirement already satisfied: numpy in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from dfply) (1.15.4)\n",
      "Requirement already satisfied: pytz>=2011k in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas->dfply) (2018.4)\n",
      "Requirement already satisfied: python-dateutil>=2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas->dfply) (2.7.3)\n",
      "Requirement already satisfied: six>=1.5 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from python-dateutil>=2->pandas->dfply) (1.11.0)\n",
      "\u001b[31mfastai 1.0.50.post1 requires nvidia-ml-py3, which is not installed.\u001b[0m\n",
      "\u001b[31mthinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.0 which is incompatible.\u001b[0m\n",
      "\u001b[31mautovizwidget 0.12.7 has requirement plotly<3.0,>=1.10.0, but you'll have plotly 3.10.0 which is incompatible.\u001b[0m\n",
      "Installing collected packages: dfply\n",
      "Successfully installed dfply-0.3.3\n",
      "\u001b[33mYou are using pip version 10.0.1, however version 19.1.1 is available.\n",
      "You should consider upgrading via the 'pip install --upgrade pip' command.\u001b[0m\n",
      "Collecting pandas_ml\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/ae/72/6d90debfcb9ea74ec00927fa7ed0204dcc560b1f9ffcd8b239daa7fd106d/pandas_ml-0.6.1-py3-none-any.whl (100kB)\n",
      "\u001b[K    100% |████████████████████████████████| 102kB 5.6MB/s a 0:00:011\n",
      "\u001b[?25hCollecting enum34 (from pandas_ml)\n",
      "  Downloading https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl\n",
      "Requirement already satisfied: pandas>=0.19.0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas_ml) (0.22.0)\n",
      "Requirement already satisfied: python-dateutil>=2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas>=0.19.0->pandas_ml) (2.7.3)\n",
      "Requirement already satisfied: numpy>=1.9.0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas>=0.19.0->pandas_ml) (1.15.4)\n",
      "Requirement already satisfied: pytz>=2011k in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas>=0.19.0->pandas_ml) (2018.4)\n",
      "Requirement already satisfied: six>=1.5 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from python-dateutil>=2->pandas>=0.19.0->pandas_ml) (1.11.0)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31mfastai 1.0.50.post1 requires nvidia-ml-py3, which is not installed.\u001b[0m\n",
      "\u001b[31mthinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.0 which is incompatible.\u001b[0m\n",
      "\u001b[31mautovizwidget 0.12.7 has requirement plotly<3.0,>=1.10.0, but you'll have plotly 3.10.0 which is incompatible.\u001b[0m\n",
      "Installing collected packages: enum34, pandas-ml\n",
      "Successfully installed enum34-1.1.6 pandas-ml-0.6.1\n",
      "\u001b[33mYou are using pip version 10.0.1, however version 19.1.1 is available.\n",
      "You should consider upgrading via the 'pip install --upgrade pip' command.\u001b[0m\n",
      "Collecting pdpbox\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/87/23/ac7da5ba1c6c03a87c412e7e7b6e91a10d6ecf4474906c3e736f93940d49/PDPbox-0.2.0.tar.gz (57.7MB)\n",
      "\u001b[K    100% |████████████████████████████████| 57.7MB 979kB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: pandas in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pdpbox) (0.22.0)\n",
      "Requirement already satisfied: numpy in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pdpbox) (1.15.4)\n",
      "Requirement already satisfied: scipy in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pdpbox) (1.1.0)\n",
      "Requirement already satisfied: matplotlib>=2.1.2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pdpbox) (2.2.2)\n",
      "Collecting joblib (from pdpbox)\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl (278kB)\n",
      "\u001b[K    100% |████████████████████████████████| 286kB 13.4MB/s ta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: psutil in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pdpbox) (5.4.5)\n",
      "Requirement already satisfied: scikit-learn in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pdpbox) (0.19.1)\n",
      "Requirement already satisfied: pytz>=2011k in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas->pdpbox) (2018.4)\n",
      "Requirement already satisfied: python-dateutil>=2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pandas->pdpbox) (2.7.3)\n",
      "Requirement already satisfied: six>=1.10 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib>=2.1.2->pdpbox) (1.11.0)\n",
      "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib>=2.1.2->pdpbox) (2.2.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib>=2.1.2->pdpbox) (0.10.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib>=2.1.2->pdpbox) (1.0.1)\n",
      "Requirement already satisfied: setuptools in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.1.2->pdpbox) (39.1.0)\n",
      "Building wheels for collected packages: pdpbox\n",
      "  Running setup.py bdist_wheel for pdpbox ... \u001b[?25ldone\n",
      "\u001b[?25h  Stored in directory: /home/ubuntu/.cache/pip/wheels/7d/08/51/63fd122b04a2c87d780464eeffb94867c75bd96a64d500a3fe\n",
      "Successfully built pdpbox\n",
      "\u001b[31mfastai 1.0.50.post1 requires nvidia-ml-py3, which is not installed.\u001b[0m\n",
      "\u001b[31mthinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.0 which is incompatible.\u001b[0m\n",
      "\u001b[31mautovizwidget 0.12.7 has requirement plotly<3.0,>=1.10.0, but you'll have plotly 3.10.0 which is incompatible.\u001b[0m\n",
      "Installing collected packages: joblib, pdpbox\n",
      "Successfully installed joblib-0.13.2 pdpbox-0.2.0\n",
      "\u001b[33mYou are using pip version 10.0.1, however version 19.1.1 is available.\n",
      "You should consider upgrading via the 'pip install --upgrade pip' command.\u001b[0m\n",
      "Collecting shap\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/b4/24/c6c06e5ebdcfce4318dd9b5a8b3f3c1f87b45670105f241a9f99aa1f39e2/shap-0.29.1.tar.gz (229kB)\n",
      "\u001b[K    100% |████████████████████████████████| 235kB 12.7MB/s ta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: numpy in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from shap) (1.15.4)\n",
      "Requirement already satisfied: scipy in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from shap) (1.1.0)\n",
      "Requirement already satisfied: scikit-learn in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from shap) (0.19.1)\n",
      "Requirement already satisfied: matplotlib in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from shap) (2.2.2)\n",
      "Requirement already satisfied: pandas in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from shap) (0.22.0)\n",
      "Requirement already satisfied: tqdm in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from shap) (4.31.1)\n",
      "Requirement already satisfied: ipython in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from shap) (6.4.0)\n",
      "Requirement already satisfied: scikit-image in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from shap) (0.13.1)\n",
      "Requirement already satisfied: cycler>=0.10 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib->shap) (0.10.0)\n",
      "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib->shap) (2.2.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib->shap) (1.0.1)\n",
      "Requirement already satisfied: six>=1.10 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib->shap) (1.11.0)\n",
      "Requirement already satisfied: python-dateutil>=2.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib->shap) (2.7.3)\n",
      "Requirement already satisfied: pytz in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from matplotlib->shap) (2018.4)\n",
      "Requirement already satisfied: pexpect; sys_platform != \"win32\" in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (4.5.0)\n",
      "Requirement already satisfied: decorator in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (4.3.0)\n",
      "Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.15 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (1.0.15)\n",
      "Requirement already satisfied: simplegeneric>0.8 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (0.8.1)\n",
      "Requirement already satisfied: jedi>=0.10 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (0.12.0)\n",
      "Requirement already satisfied: traitlets>=4.2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (4.3.2)\n",
      "Requirement already satisfied: backcall in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (0.1.0)\n",
      "Requirement already satisfied: pickleshare in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (0.7.4)\n",
      "Requirement already satisfied: setuptools>=18.5 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (39.1.0)\n",
      "Requirement already satisfied: pygments in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from ipython->shap) (2.2.0)\n",
      "Requirement already satisfied: networkx>=1.8 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from scikit-image->shap) (2.1)\n",
      "Requirement already satisfied: pillow>=2.1.0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from scikit-image->shap) (5.2.0)\n",
      "Requirement already satisfied: PyWavelets>=0.4.0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from scikit-image->shap) (0.5.2)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pexpect; sys_platform != \"win32\"->ipython->shap) (0.5.2)\n",
      "Requirement already satisfied: wcwidth in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.15->ipython->shap) (0.1.7)\n",
      "Requirement already satisfied: parso>=0.2.0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from jedi>=0.10->ipython->shap) (0.2.0)\n",
      "Requirement already satisfied: ipython_genutils in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from traitlets>=4.2->ipython->shap) (0.2.0)\n",
      "Building wheels for collected packages: shap\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Running setup.py bdist_wheel for shap ... \u001b[?25ldone\n",
      "\u001b[?25h  Stored in directory: /home/ubuntu/.cache/pip/wheels/93/3f/4a/331cf71b5043416aeba0df795e7c204c7ad277673f1938d11b\n",
      "Successfully built shap\n",
      "\u001b[31mfastai 1.0.50.post1 requires nvidia-ml-py3, which is not installed.\u001b[0m\n",
      "\u001b[31mthinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.0 which is incompatible.\u001b[0m\n",
      "\u001b[31mautovizwidget 0.12.7 has requirement plotly<3.0,>=1.10.0, but you'll have plotly 3.10.0 which is incompatible.\u001b[0m\n",
      "Installing collected packages: shap\n",
      "Successfully installed shap-0.29.1\n",
      "\u001b[33mYou are using pip version 10.0.1, however version 19.1.1 is available.\n",
      "You should consider upgrading via the 'pip install --upgrade pip' command.\u001b[0m\n",
      "Collecting pixiedust\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/bc/a8/e84b2ed12ee387589c099734b6f914a520e1fef2733c955982623080e813/pixiedust-1.1.17.tar.gz (197kB)\n",
      "\u001b[K    100% |████████████████████████████████| 204kB 29.5MB/s ta 0:00:01\n",
      "\u001b[?25hCollecting mpld3 (from pixiedust)\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/91/95/a52d3a83d0a29ba0d6898f6727e9858fe7a43f6c2ce81a5fe7e05f0f4912/mpld3-0.3.tar.gz (788kB)\n",
      "\u001b[K    100% |████████████████████████████████| 798kB 24.5MB/s ta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: lxml in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pixiedust) (4.2.1)\n",
      "Collecting geojson (from pixiedust)\n",
      "  Downloading https://files.pythonhosted.org/packages/f1/34/bc3a65faabce27a7faa755ab08d811207a4fc438f77ef09c229fc022d778/geojson-2.4.1-py2.py3-none-any.whl\n",
      "Collecting astunparse (from pixiedust)\n",
      "  Downloading https://files.pythonhosted.org/packages/2e/37/5dd0dd89b87bb5f0f32a7e775458412c52d78f230ab8d0c65df6aabc4479/astunparse-1.6.2-py2.py3-none-any.whl\n",
      "Collecting markdown (from pixiedust)\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl (87kB)\n",
      "\u001b[K    100% |████████████████████████████████| 92kB 33.2MB/s ta 0:00:01\n",
      "\u001b[?25hCollecting colour (from pixiedust)\n",
      "  Downloading https://files.pythonhosted.org/packages/74/46/e81907704ab203206769dee1385dc77e1407576ff8f50a0681d0a6b541be/colour-0.1.5-py2.py3-none-any.whl\n",
      "Requirement already satisfied: requests in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from pixiedust) (2.20.1)\n",
      "Requirement already satisfied: six<2.0,>=1.6.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from astunparse->pixiedust) (1.11.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from astunparse->pixiedust) (0.31.1)\n",
      "Requirement already satisfied: setuptools>=36 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from markdown->pixiedust) (39.1.0)\n",
      "Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from requests->pixiedust) (1.23)\n",
      "Requirement already satisfied: idna<2.8,>=2.5 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from requests->pixiedust) (2.6)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from requests->pixiedust) (2019.3.9)\n",
      "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from requests->pixiedust) (3.0.4)\n",
      "Building wheels for collected packages: pixiedust, mpld3\n",
      "  Running setup.py bdist_wheel for pixiedust ... \u001b[?25ldone\n",
      "\u001b[?25h  Stored in directory: /home/ubuntu/.cache/pip/wheels/25/fa/a5/09c1e8f4c91b34c5f7f4ac6e41be81dd0667030a2372546a8d\n",
      "  Running setup.py bdist_wheel for mpld3 ... \u001b[?25ldone\n",
      "\u001b[?25h  Stored in directory: /home/ubuntu/.cache/pip/wheels/c0/47/fb/8a64f89aecfe0059830479308ad42d62e898a3e3cefdf6ba28\n",
      "Successfully built pixiedust mpld3\n",
      "\u001b[31mfastai 1.0.50.post1 requires nvidia-ml-py3, which is not installed.\u001b[0m\n",
      "\u001b[31mthinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.0 which is incompatible.\u001b[0m\n",
      "\u001b[31mautovizwidget 0.12.7 has requirement plotly<3.0,>=1.10.0, but you'll have plotly 3.10.0 which is incompatible.\u001b[0m\n",
      "Installing collected packages: mpld3, geojson, astunparse, markdown, colour, pixiedust\n",
      "Successfully installed astunparse-1.6.2 colour-0.1.5 geojson-2.4.1 markdown-3.1.1 mpld3-0.3 pixiedust-1.1.17\n",
      "\u001b[33mYou are using pip version 10.0.1, however version 19.1.1 is available.\n",
      "You should consider upgrading via the 'pip install --upgrade pip' command.\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "! pip install xgboost\n",
    "! pip install plotly_express\n",
    "! pip install dfply\n",
    "! pip install pandas_ml #For confusion matrix\n",
    "! pip install pdpbox\n",
    "! pip install shap\n",
    "! pip install pixiedust"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning:\n",
      "\n",
      "numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pixiedust database opened successfully\n",
      "Table VERSION_TRACKER created successfully\n",
      "Table METRICS_TRACKER created successfully\n",
      "\n",
      "Share anonymous install statistics? (opt-out instructions)\n",
      "\n",
      "PixieDust will record metadata on its environment the next time the package is installed or updated. The data is anonymized and aggregated to help plan for future releases, and records only the following values:\n",
      "\n",
      "{\n",
      "   \"data_sent\": currentDate,\n",
      "   \"runtime\": \"python\",\n",
      "   \"application_version\": currentPixiedustVersion,\n",
      "   \"space_id\": nonIdentifyingUniqueId,\n",
      "   \"config\": {\n",
      "       \"repository_id\": \"https://github.com/ibm-watson-data-lab/pixiedust\",\n",
      "       \"target_runtimes\": [\"Data Science Experience\"],\n",
      "       \"event_id\": \"web\",\n",
      "       \"event_organizer\": \"dev-journeys\"\n",
      "   }\n",
      "}\n",
      "You can opt out by calling pixiedust.optOut() in a new cell.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "        <div style=\"margin:10px\">\n",
       "            <a href=\"https://github.com/ibm-watson-data-lab/pixiedust\" target=\"_new\">\n",
       "                <img src=\"https://github.com/ibm-watson-data-lab/pixiedust/raw/master/docs/_static/pd_icon32.png\" style=\"float:left;margin-right:10px\"/>\n",
       "            </a>\n",
       "            <span>Pixiedust version 1.1.17</span>\n",
       "        </div>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31mPixiedust runtime updated. Please restart kernel\u001b[0m\n",
      "Table USER_PREFERENCES created successfully\n",
      "Table service_connections created successfully\n"
     ]
    }
   ],
   "source": [
    "import xgboost as xgb\n",
    "import plotly_express as px\n",
    "from dfply import *\n",
    "import shap\n",
    "import pixiedust"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cloning into 'DS_Explorations'...\n",
      "remote: Enumerating objects: 455, done.\u001b[K\n",
      "remote: Counting objects: 100% (455/455), done.\u001b[K\n",
      "remote: Compressing objects: 100% (446/446), done.\u001b[K\n",
      "remote: Total 510 (delta 12), reused 447 (delta 6), pack-reused 55\u001b[K\n",
      "Receiving objects: 100% (510/510), 50.29 MiB | 45.34 MiB/s, done.\n",
      "Resolving deltas: 100% (31/31), done.\n",
      "Checking connectivity... done.\n"
     ]
    }
   ],
   "source": [
    "#! git clone https://github.com/Archisman-Roy/DS_Explorations.git"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Environment (conda_pytorch_p36)",
   "language": "python",
   "name": "conda_pytorch_p36"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
